name: echo_hello  # Workflow name

on: push  # Trigger on push
  
jobs:
  echo_hello:  # Job name
    runs-on: ubuntu-latest  # Runner Selection
    steps:
      - name: hello world with echo  # step 1
        run: echo Hello, world! Github Actions
        
      - name: hello world with CLI  # step 2
        run: python -c "print('Hello, world! Github Actions step 2')"
        
      - name: python version check
        run: python --version
        
      - name: python version upgrade (3.9)
        run: sudo apt install python3.9

      - name: python version check
        run: python3.9 --version
