name: echo_hello  # Workflow name

on: push  # Trigger on push
  
jobs:
  echo_hello:  # Job name
    runs-on: ubuntu-latest  # Runner Selection
    steps:
      - name: Setup Python Ver. to 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.9"

      - name: python version check
        run: python --version
